### ISSUE TITLE
Performance with cacheResponse: true in Firefox and Safari vs Chrome

### ISSUE THREAD

**Issue by hardyti** [jmdobry/angular-data#282] opened 2015-01-06 00:37 UTC
When using cacheResponse: true, performance on an initial load of data is fine in Chrome. However, performance pegs one CPU core for minutes at a time in both Firefox and Safari. Using the Firefox javascript profiler, I see that 77.48% of the time is in angular-cache.js:327 calling DSBinaryHeap.prototype.remove at angular-cache.js:142, calling angular.equals.

angular.equals is the code that is taking all the CPU time - but DSBinaryHeap.prototype.remove seems suboptimal to me as an O(n) search?  I'm not talking about a lot of records in the cache here (maybe 1000, I think, at least in terms of rows being returned that shoudl get added....) and it is extremely slow except on Chrome. Any ideas?

![screen shot 2015-01-05 at 4 29 45 pm](https://cloud.githubusercontent.com/assets/9354592/5622484/11474dc2-94f9-11e4-89c3-5325ab96d0a7.png)

    DSBinaryHeap.prototype.remove = function (node) {
      var length = this.heap.length;
      for (var i = 0; i < length; i++) {
        if (angular.equals(this.heap[i], node)) {
          var removed = this.heap[i],
            end = this.heap.pop();
          if (i !== length - 1) {
            this.heap[i] = end;
            bubbleUp(this.heap, this.weightFunc, i);
            bubbleDown(this.heap, this.weightFunc, i);
          }
          return removed;
        }
      }
      return null;    
    };

**Comment by jmdobry** [comment] 2015-01-06 01:13
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-data, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-data).

**Closed by jmdobry** 2015-01-06 01:13 UTC

**Comment by hardyti** [comment] 2015-01-06 17:12
Okay, I'm working on a plinkr to see if I can provide you something reproducible. Perhaps the problem is actually the implementation of angular.equals. I see that the profile shows only 2207 calls to that function but it took 253 seconds. That's an astounding 11 ms per call. It's fast in Chrome, but terrible in Firefox and Safari.

**Comment by jmdobry** [comment] 2015-01-06 17:16
A plnkr would be great

**Comment by hardyti** [comment] 2015-01-06 17:42
I'll see what I can come up with. Is there a reason the cache removal isn't just comparing the 'id' or 'primary key' of each entry in the cache against the new node, rather than doing a full angular.equals on the object? It would seem best if the cache was a map where the key was the primary key, for efficient lookup and removal. From the DSBinaryHeap above if seems like a simple list with full value comparison on operations.

**Comment by jmdobry** [comment] 2015-01-06 18:09
Angular-data is ignorant of the internal implementation of angular-cache. And likewise, I cannot couple angular-cache's internals to angular-data's implementation. Each are trying to solve a different problem in a general way.

`angular.equals` should not be a problem because it first tries strict equals (`===`) when testing for equality, and since angular-data relies on identity-mapping, `===` will always be the first expression to be `true` if the objects are equal. If they're not equal than it will quickly discover an attribute that differs between the two objects.

You don't have hundreds of objects all with the same property values do you?

Also, switching to [js-data](http://www.js-data.io/) + [js-data-angular](http://www.js-data.io/docs/js-data-angular) (angular-data 2.0) might help your performance problems, as js-data does not use angular-cache, but has an improved internal way of handling item expiration stuff. Since js-data doesn't use angular-cache (which has to solve the problem generally), js-data can solve the problem in a way that tailor's to js-data's needs. js-data uses just the strict equals operator when testing for equality in its heap's `remove` method.

**Comment by hardyti** [comment] 2015-01-06 18:28
Thanks for the help - I'm dealing with hundreds of moderately complex objects each with the same set of properties, but the values probably differ in almost all cases. The 'key' is different for each, and that's a property on the top level object for each row. For example, I see the problem with a list of "Users" in a data grid, each with id, first/last name, nested 'role' object, login time, etc.  At the bottom I've pasted JSON for one of the example objects in the cache (although note that it is not a "pojo" so it may be comparing functions as well in equals? The object and all nested objects are decorated with quite a few functions).

I'm digging into the code a bit and it seems like $$expiresHeap and $$lruHeap are what use the DSBinaryHeap, while $$data or $$storage don't. I'm investigating whether setting deleteOnExpire to 'none' might work around this (if we can live with that)...thanks for the feedback.

JSON dump for an example "node" passed to DSBinaryHeap.prototype.remove, which takes forever in equals on non-Chrome browsers. You'd expect it to compare 'key' first and be O(n) but relatively fast on each iteration.

    {"key":"1","value":{"id":1,"name":"xxxxxxxx","domain":"","group_id":0,"deleted_flag":false,"last_login":"2015-01-06T01:55:40","active_session_count":null,"local_admin_flag":1,"permissions":[{"permission":"admin"},{"permission":"sensor_read"},{"permission":"sensor_write"},{"permission":"question_read"},{"permission":"question_write"},{"permission":"action_read"},{"permission":"action_write"},{"permission":"action_approval"},{"permission":"notification_write"},{"permission":"clients_read"},{"permission":"question_log_read"},{"permission":"content_admin"}],"roles":[{"id":1,"name":"Administrator","description":"...","permissions":[{"permission":"admin"},{"permission":"sensor_read"},{"permission":"sensor_write"},{"permission":"question_read"},{"permission":"question_write"},{"permission":"action_read"},{"permission":"action_write"},{"permission":"action_approval"},{"permission":"notification_write"},{"permission":"clients_read"},{"permission":"question_log_read"},{"permission":"content_admin"}]}],"metadata":[]},"created":1420568429398,"accessed":1420568429398,"expires":1.7976931348623157e+308}

**Comment by jmdobry** [comment] 2015-01-06 18:39
If instead of expiring individual items, you could try `cacheFlushInterval` to clear the whole cache at a time, which should be faster.

The object that have lots of functions: did you add the functions as properties of the functions? Or are they inheriting the functions via the prototype?

**Comment by hardyti** [comment] 2015-01-06 18:46
Looking at the same object for which I pasted the json above, besides a "toObject" function on each instance (which I can probably move to the prototype), the functions are all on the prototype, and it's on the order of a dozen (except for the one Array property, which of course has an extensive prototype).

**Comment by jmdobry** [comment] 2015-01-06 18:53
I'll wait for the plnkr.

**Comment by hardyti** [comment] 2015-01-07 01:05
I'm getting closer to a plnkr, but can't quite reproduce it exactly. I'll post when I do.

I did get more detailed profiling output from Firefox and I can tell that in Firefox 96% of the time is spent evaluating isWindow(o1) and isWindow(o2) inside angular.equals(). Not sure why that is so costly, but unfortunately angular.equals evaluates isScope and isWindow on both objects *before* it gets into evaluating object properties (of which 'key' is the first property and returns false quickly when they mismatch 99.9...% of the time). I hacked in a short-circuit to angular.equals where if o1 is an "object", then the first thing it does is short-circuit on "return angular.equals(o1.key, o2.key)" if o2 is also an object, assuming the 'key' is sufficient and special (yuck, but...). That removed all of the angular.equals() time in Firefox (though there is yet another problem...it went from 90+ seconds of CPU usage to about 7 seconds, which is still terrible when Chrome is well under a second).

**Comment by hardyti** [comment] 2015-01-07 19:37
I deleted my last comment - got a little sidetracked with one weird profiler result. I now know what causes this problem, and we have a workaround. Let me describe it. I don't yet have a plnkr, but this definitely describes the cause:

Essentially all of the CPU time in Firefox is spent in the angular-data.js digest loop. Every 1/10th of a second, that loop goes through the entire cache and looks for added/removed/changed properties on every object in the cache (see diffObjectFromOldObject).  On Chrome, this digest loop is actually not performed because Object.observe is used (see the following code in $get). Chrome is the only brower that supports this experimental feature (see "browser compatibility" at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe#Browser_compatibility)

From $get in angular-data.js (note: changing the hard-coded 100 below to 5000 fixes the problem for us):

      if (typeof Object.observe !== 'function' ||
        typeof Array.observe !== 'function') {
        $rootScope.$watch(function () {
          // Throttle angular-data's digest loop to tenths of a second
          return new Date().getTime() / 100 | 0;
        }, function () {
          DS.digest();
        });
      }

1/10th of a second is not even enough time for it go through a 50-item cache I was testing with and find all diffs, with Firefox. Therefore, it pegs the CPU forever. Changing the digest time to every 5 seconds completely fixed this for us, and I don't even notice a lag every 5 seconds. I'm looking at a clean way to make that configurable or disable it (I'm not sure we even need this feature).

I guess if you don't consider this a bug, it would a good enhancement to make the digest interval configurable. 100ms is too short for it to be repeating such an expensive block of code.

Thanks!

Here's a profile that is reproducible with my 50-item cache - every time I refresh the page I see this:

![screen shot 2015-01-07 at 11 30 58 am](https://cloud.githubusercontent.com/assets/9354592/5651989/62428426-9661-11e4-93c8-a9ffdbcec924.png)

**Comment by jmdobry** [comment] 2015-01-07 20:52
I will make the throttle configurable. See #283.

Here's how this works:
```js

// Take advantage of Object.observe if it's available
if (typeof Object.observe !== 'function' || typeof Array.observe !== 'function') {

  // this $watch function is only fired when your Angular app's 
  // $rootScope goes through a digest loop.
  $rootScope.$watch(function () {

    // This is to throttle back (reduce) how many times this $watch 
    // function causes the change function below to fire
    // example: your Angular app experiences 8 digest loops on the 
    // $rootScope over 100ms. So for those 100 ms this code ensures 
    // that the change function below will fire only once during 
    // that 100ms instead of ~8 times
    return new Date().getTime() / 100 | 0;
  }, function () {

    // This tells observe-js to collect changes and report them to 
    // the registered callbacks
    // The callbacks simply update the lastModified timestamp for 
    // any items that have been changed
    // and update any computed properties accordingly
    // The callbacks will not trigger more digest loops unless 
    // you're $watching lastModified timestamps or computed properties
    // This has absolutely no effect when Object.observe is present
    // and will not trigger more loops unless you're watching computed
    // properties or lastModified timestamps
    DS.digest();
  });
}
```

You can examine the observer callback [here](https://github.com/jmdobry/angular-data/blob/master/src/datastore/sync_methods/inject.js#L31).

You haven't posted an example code, so I have to ask:

- Are you using computed properties?
- Are you $watching lastModified timestamps anywhere? e.g. `$scope.$watch(function () { return User.lastModified(4); }, ...);`
- Are you manually triggering digest loops on your $rootScope?

I would make sure that you're not inadvertantly triggering lots and lots of digest loops on your $rootScope. This can be caused by $watch callbacks that are not idempotent. Sometimes the reasons are inexplicable or hard to find. Sometimes it's a magic wrong combination of directives on a single element. If you're doing data tables, then you probably want to be using some form of [bindonce](https://github.com/Pasvaz/bindonce). Also try debugging with AngularJS-Batarang. It can help reveal how many digest loops are happening on your app's $rootScope and what might be triggering them.

Because of how `DS.inject` works, when your large array of items gets injected, it will all happen inside a single digest loop. Done.

I have actually seen this performance issue before, and in every case (so far) it was caused by something in the app triggering an inordinate amount of digests. I've seen it with other users of Angular-data and in our apps at work.

Curse dirty-checking.

**Comment by hardyti** [comment] 2015-01-07 21:05
Thanks. I don't think we are doing anything super unusual (no computed properties, no extra $watch of our own that I know of) -- although we are using a kendo grid component to display all the objects, so all of the objects are effectively tied to an ng-model from that. That may be why my current plunker doesn't demonstrate the issue - I'm going to add an ng-model for each in a bit to see if that changes things. I looked into using bindonce since the grid is usually immutable, but have not yet done so (didn't need to do that Chrome, once I added paging). We do page our data, so I think we should only have about 25 rows * ~10 columns bound from that. But it's all enough to throw Firefox off the deep end. I'm trying to get a plunker together with example code, after I work around the issue first. That would be better than trying to post our actual code.
