### ISSUE TITLE
findAll and filter params

### ISSUE THREAD

**Issue by matuszeman** [jmdobry/angular-data#290] opened 2015-01-15 15:28 UTC
Version: 1.5.3

When I run a code below (in coffescript) I only get some results from 'data' console.log. Others are empty arrays.

```
      params = {
        where: {
          author: {
            '==': 'xxx'
          }
        }
      }

      DS.findAll('account', params).then((res) ->
        console.log('data', res);

        DS.findAll('account', params).then((findAll) ->
          console.log('findAll', findAll)
        )

        console.log('filter', DS.filter('account', params))
      )

```

**Comment by jmdobry** [comment] 2015-01-15 16:14
Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of Angular, Angular-data, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [mailing list](https://groups.google.com/forum/?fromgroups#!forum/angular-data).

**Closed by jmdobry** 2015-01-15 16:14 UTC

**Comment by matuszeman** [comment] 2015-01-15 16:32
I read all documentation and it seems that all console logs should return same objects, while second DS.findAll would not even fetch data from the server but get it from local cache.
I'm new to angular-data so I hoped you're going to confirm at least what expected behaviour should be like if not like above.
I can obviously provide fiddle, versions etc and maybe fix the issue too if this is considered to be intended behaviour.

Angular version: 1.2.28
"angular-data": "1.5.3",
 "angular-cache": "3.2.4"

**Comment by jmdobry** [comment] 2015-01-15 16:43
Intended behavior is that you should get the same data in all console.logs. My suspicion that your server does not interpret `{ where: { author: { '==': 'xxx' } } }` the same way that `DS.filter`. does. Try using the simple params instead: `{author: 'xxx' }`.

As it is, I don't have near enough information to help you debug.

**Comment by sheetalmjkrishna** [comment] 2019-08-16 22:57
I'm trying to use findAll to get some records and I'd like to filter by multiple values of a single parameter.
This works:
`Rule.findAll({ property: 5596 }).then(function(response) {//stuff})`

I want something like:
`Rule.findAll({ property: [5596,1234, 6789...] }).then(function(response) {//stuff})`

But that doesn't work. How do I achieve that?

**Comment by crobinson42** [comment] 2019-08-16 23:01
This is better suited to be posted in stackoverflow.com

**Comment by sheetalmjkrishna** [comment] 2019-08-16 23:10
> This is better suited to be posted in stackoverflow.com

I have already, but I haven't received any responses.

[https://stackoverflow.com/questions/57530986/how-do-we-filter-using-ds-findall-when-you-have-multiple-values-for-a-parameter](url)
